---
apiVersion: v1
kind: Service
metadata:
  name: compute-interest-api
  labels:
    app: office-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office-space
    tier: compute
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-interest-api
  labels:
    app: office-space
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: office-space
      tier: compute
  template:
    metadata:
      labels:
        app: office-space
        tier: compute
    spec:
      containers:
        - image: mosttiee/compute-interest-api:latest
          imagePullPolicy: Always
          name: compute-interest-api
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: password
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: host
            - name: MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: port
          ports:
            - containerPort: 8080
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
