---
language: python
python: 2.7
group: stable
os: linux

services:
  - docker

env:
  - TEST_RUN="./tests/test-minikube.sh"
  - TEST_RUN="./tests/test-kubernetes.sh"

before_install:
  - sudo apt-get install shellcheck
  - pip install yamllint

install:
  - "./scripts/install_bx.sh"
  - "./scripts/bx_auth.sh"

before_script:
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

script: "$TEST_RUN"
