---
apiVersion: v1
kind: Service
metadata:
  name: account-database
  labels:
    app: office-space
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: office-space
    tier: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-database
  labels:
    app: office-space
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: office-space
      tier: database
  template:
    metadata:
      labels:
        app: office-space
        tier: database
    spec:
      containers:
        - image: hypriot/rpi-mysql
          name: account-database
          env:
            - name: MYSQL_USER
              value: michaelbolton
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: dockercon2017
          ports:
            - containerPort: 3306
              name: db
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
