apiVersion: v1
kind: PersistentVolume
metadata:
  name: account-database-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.92
    path: "/mnt/accountDB"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-database-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi